config/routes.rb
Rails.application.routes.draw do
  resources :players do
    resources :games, shallow: true
  end

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id         :integer          not null, primary key
#  player_id  :integer
#  color      :string           not null
#  guess      :string
#  won        :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Game < ActiveRecord::Base
  validates :color, inclusion: { in: ['red', 'green', 'blue'] }

  belongs_to :player

  def self.random_color
    Game.colors.sample
  end

  def self.colors
    ['red', 'green', 'blue']
  end

  def to_s
    "Your guess: " + guess + ", Hidden color: " + color
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Player < ActiveRecord::Base
  attr_reader :password

  validates :email, presence: true, uniqueness: true
  # allow nil allows us to validate players during things other
  # than password change, since @password won't be set any other place
  validates :password, length: { minimum: 5, allow_nil: true }

  has_many :games

  # Player.find_by_credentials(email: params[:email], password: params[:password])
  def self.find_by_credentials(args = {})
    player = Player.find_by(email: args[:email])
    return nil unless player

    # if player.is_password?(args[:password])
    #   return player
    # else
    #   return nil
    # end
    return player.is_password?(args[:password]) ? player : nil
  end

  def password=(pwd)
    @password = pwd  # only for validation on pw create or change
    self.password_digest = BCrypt::Password.create(pwd)
  end

  def is_password?(pwd)
    BCrypt::Password.new(self.password_digest).is_password?(pwd)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @player = Player.find(params[:player_id])
    @game = Game.new(player_id: @player.id)
  end

  def create
    @player = Player.find(params[:player_id])

    @game = Game.new(game_params)
    @game.won = (@game.guess == @game.color)

    if @game.save
      redirect_to @player
    else
      render :new
    end
  end

  private

  def game_params
    params.require(:game).permit(:guess).merge({
      player_id: params[:player_id],
      color: Game.random_color
      })
  end

  # params.require(:game).permit(:color) will look like
  # { guess: "blue" }
  # so by merging, we'll upgrade game_params to look like
  # { guess: "blue", player_id: 3, color: "red" }
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])

    @games = @player.games.order(created_at: :desc).group_by do |game|
      game.won
    end

    @last_game = @player.games.order(:created_at).last
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to player_url(@player)
    else
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to player_url(@player)
    else
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    redirect_to players_url
  end

  private

  def player_params
    params.require(:player).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper

  def winning_percent(player)
    return 0 if player.games.none?

    win_count = player.games.where(won: true).count
    total_count = player.games.count

    return 100.0 * win_count / total_count
  end
  
end

app/views/games/new.html.erb
<h1>Welcome, <%= @player.email %>, do you want to play a game?</h1>

<%= form_for @game, url: player_games_url do |game| %>
  <%= game.label :guess %>
  <%= game.select :guess, Game.colors %>

  <%= game.submit "I've made my choice!" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuessingGame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/edit.html.erb
<h1>Edit Page</h1>

<%= form_for @player do |player| %>
  <%= player.label :email, "Your email" %>
  <%= player.text_field :email, value: @player.email %>

  <%= player.submit "DO YOU _STILL_ WANT TO PLAY A GAME?" %>
<% end %>

app/views/players/index.html.erb
<h1>Your players are...</h1>

<% @players.each do |player| %>
  <p>
    <%= link_to(player.email, player_url(player)) %>
    <%= button_to "Remove Player", { controller: :players, action: :destroy, id: player.id }, method: :delete %>
  </p>
<% end %>

<hr>

<%= link_to "Add a player", new_player_url %>

app/views/players/new.html.erb
<h1>New Page</h1>

<%= form_for @player do |player| %>
  <%= player.label :email, "Your email" %>
  <%= player.text_field :email, value: @player.email %>

  <%= player.label :password, "Your password" %>
  <%= player.password_field :password, value: @player.password %>

  <%= player.submit "DO YOU WANT TO PLAY A GAME?" %>
<% end %>

app/views/players/show.html.erb
<h1><%= @player.email %> ☠<%= link_to("edit", edit_player_url(@player)) %>☠</h1>

<h2>Your Games (<%= link_to("Play another", new_player_game_url(@player)) %>)</h2>

<h3>You've won <%= winning_percent(@player).round(1) %>% of the time.</h3>

<% @games.each do |won, game_list| %>
  <p class="<%= won ? "winning-game" : "losing-game" %>">
    <% game_list.each do |game| %>
      <% if game.id == @last_game.id %>
        <span class="last-game">➳ <%= game %>, at <%= game.created_at.strftime("%T") %> <br/></span>
      <% else %>
        <%= game %>, at <%= game.created_at.strftime("%T") %> <br/>
      <% end %>
    <% end %>
  </p>
<% end %>

<hr>

<%= link_to "All Players who Haven't Expired", players_url %>